USER-SUPPLIED VALUES:
USER-SUPPLIED VALUES: null
image:
  repository: savantabvairflow.azurecr.io/external-secrets/external-secrets
installCRDs: true

# This configures the 'external-secrets-webhook' deployment
webhook:
  image:
    repository: savantabvairflow.azurecr.io/external-secrets/external-secrets
    tag: v0.19.0

# This configures the 'external-secrets-cert-controller' deployment
certController:
  image:
    repository: savantabvairflow.azurecr.io/external-secrets/external-secrets
    tag: v0.19.0
